### PR TITLE
Release It configuration

### PR DESCRIPTION
**Pull request by antonjb**
### Problem

The package isn't published to GitHub Packages so is failing with npm install

### Solution

Adds Release It configuration, matching Marketist, so that the library
is published to GitHub packages and NPM.

### Test Plan

I wasn't able to do run `--dry-run` as I'm not a collaborator on the package. @henningmu or @miottid is this something you can resolve so I can test?

Alternatively if you are a contributor, run `npx release-it --dry-run` and we should see successful results of some fashion.

### CODE REVIEW

**Comment by miottid** [comment]
I just tried but I‘m not a collaborator either.

**Comment by henningmu** [comment]
Will try to test later – but I'm not sure how to add y'all. This is what I'm seeing:
Screenshot 2021-11-29 at 12 37 54

**Comment by antonjb** [comment]
I think it's on the NPM side? That's where the error appears to originate from

**Comment by henningmu** [comment]
Running `npx release-it --dry-run` just hangs on the publish step, when ctrl+c aborting it, it looks successful though 🙃
Anyway, I added the whole fullstack team on npm hopefully that worked. If it doesn't we should look into a CI based workflow for releases as we have solved this problem already for multiple other repos 👍

**Comment by antonjb** [comment]
@henningmu when I tried to accept the invite to the npm organisation I get a 404 error 😩 Any chance you could send it through again? Unsure what's going wrong.

> we have solved this problem already for multiple other repos

Who is a good person to discuss that with?

**Comment by JefCurtis** [comment]
I just attempted to run the same command and I'm seeing: 

2021-11-29 at 15 53 19@2x

**Comment by antonjb** [comment]
@JefCurtis did you get the npm invite from Henning?

**Comment by antonjb** [comment]
I have added the same token setup as Marketist and will try that but I need to merge.

**Comment by JefCurtis** [comment]
> @JefCurtis did you get the npm invite from Henning?

Yes, I've got it now 🙈

**Pull request merged**
